README.md

Add emacs-jp

---

README.md

add バンクーバー日本人ソフトウェアエンジニア

---

README.md

added Nuxt

---

README.md

add 鹿児島ITエンジニア

---

README.md

カテゴリはよいものが思いつきませんでしたので一旦Etcに含めております...

Add sudo-jp community

---

README.md

add Flutter

---

README.md

Add [SATySFi](https://github.com/gfngfn/SATySFi)

Add SATySFi

---

README.md

Add IE11を偲ぶ会

---

README.md

Hey!
add [Elixir](https://elixir-lang.org/)!
[We are the Alchemists, my friends](https://www.youtube.com/watch?v=04854XqcfCY)!!!
This repository is Awesome!
Hope this helps.

add elixir

---

README.md

[OSS 日本語 L10n](https://twitter.com/i/communities/1498961283546157061) を追加しました

OSS 日本語 L10n 追加

---

README.md

Add プログラミング言語処理系

---

README.md

プログラマー界隈@育児のコミュ主です。公開コミュニティとはいえ自分のFF関係を大きく超えてまで広めたいわけではないので削除してほしいです。

remove プログラマー界隈@育児

---

README.md

Thanks for this repository! I added Julia言語 Twitter community.
https://twitter.com/i/communities/1499390501467811845

Add Julia言語

---

README.md

Thank you for making this repository. I added "Julia Programming Language".

Add "Julia Programming Language"

---

README.md

Add 自作キーボード communities
https://twitter.com/i/communities/1495468692813287425

Add 自作キーボード communities

---

README.md

https://twitter.com/i/communities/1497545442023944192

Add WebAssembly

---

README.md

Thank you for making this repository. 
I added "Java" and "Spring Framework".

Add "Java", "Spring Framework"

---

README.md

サバイバルTypeScript 追加

---

README.md

https://twitter.com/i/communities/1498540422154821633
ネットワーク自動化コミュニティの追加PRです。よろしくお願いします。

add ネットワーク自動化

---

README.md

Linuxカーネルコミュニティの追加です。
よろしくお願いします。

Linuxカーネルコミュニティの追加

---

README.md

まだ人が集められてないのですが・・・
よろしくお願いします 🙇 
https://twitter.com/i/communities/1498123338975092742

Add 自宅サーバの会

---

README.md

Scalaの日本語コミュニティを作成しました。追加頂ければ幸いです。
よろしくおねがいします。 
https://twitter.com/i/communities/1500072882822868998

Add Scala JP

---

README.md

先ほど作られたばかりの若いコミュニティですが、追加していただければ幸いです。
カテゴリは必要であれば変更してください！

Added community:「競技プログラミング」

---

README.md

added `ux & product design` spaces link

added ux and product design

---

README.md

`Rust Programming Language`(英語版コミュニティ)を追加しました。

update. `Rust Programming Language` comunityを追加

---

README.md

Angular, RxJS, DevReljp 追加しました。

Angular, RxJS, DevReljp 追加

---

README.md

CHIRIMEN Open Hardware コミュニティ追加しました。

CHIRIMEN Open Hardware コミュニティ追加

---

README.md

Gunma.web Twitter Community 追加

Gunma.web Twitter Community 追加

---

README.md

DBREJPのコミュニティを追加させていただきました。
お手数ですが内容及び記載順序についてご確認頂きたく、よろしくお願いいたします。

add: add DBREJP Community

---

README.md

add Vue.js Community
